# Generated by Django 5.0.3 on 2024-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeViewer', '0003_alter_user_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
